// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskAnalyzer.Api.Data;

#nullable disable

namespace RiskAnalyzer.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501000000_AddMLSeverityWeightAndRiskMetrics")]
    partial class AddMLSeverityWeightAndRiskMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RiskAnalyzer.Api.Models.ImageAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnalysisDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Categories")
                        .HasColumnType("longtext");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RiskAction")
                        .IsRequired()
                        .HasDefaultValue("Review")
                        .HasColumnType("longtext")
                        .HasComment("Action to take: Auto-Block, Review, Allow");

                    b.Property<string>("RiskColor")
                        .IsRequired()
                        .HasDefaultValue("yellow")
                        .HasColumnType("longtext")
                        .HasComment("UI color code: green (safe), yellow (warning), red (danger)");

                    b.Property<float>("RiskScore")
                        .HasColumnType("float");

                    b.Property<int>("SeverityWeight")
                        .HasColumnType("int")
                        .HasComment("Severity weight for risk category (0-10 scale)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ImageAnalyses");
                });

            modelBuilder.Entity("RiskAnalyzer.Api.Models.AnalysisTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<Guid>("ImageAnalysisId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ImageAnalysisId");

                    b.ToTable("AnalysisTags");
                });

            modelBuilder.Entity("RiskAnalyzer.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RiskAnalyzer.Api.Models.AnalysisTag", b =>
                {
                    b.HasOne("RiskAnalyzer.Api.Models.ImageAnalysis", "ImageAnalysis")
                        .WithMany("Tags")
                        .HasForeignKey("ImageAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageAnalysis");
                });

            modelBuilder.Entity("RiskAnalyzer.Api.Models.ImageAnalysis", b =>
                {
                    b.HasOne("RiskAnalyzer.Api.Models.User", "User")
                        .WithMany("ImageAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RiskAnalyzer.Api.Models.ImageAnalysis", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("RiskAnalyzer.Api.Models.User", b =>
                {
                    b.Navigation("ImageAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
